"""Add error tracking table

Revision ID: 4f1bcacdac65
Revises: 5ce81b573e35
Create Date: 2025-02-04 12:49:08.242833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f1bcacdac65'
down_revision: Union[str, None] = '5ce81b573e35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('errors_employee_id_fkey', 'errors', type_='foreignkey')
    op.drop_column('errors', 'employee_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('errors', sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('errors_employee_id_fkey', 'errors', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###
